import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React, { cache } from "react";
import {
  baseLocale,
  cookieName,
  getLocale,
  isLocale,
  Locale,
  overwriteGetLocale,
} from "@/paraglide/runtime";
import Navbar from "@/components/Navbar";
import LangSelector from "@/components/LangSelector";
import { cookies, headers } from "next/headers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: "noindex"
};

const ssrLocale = cache((): { locale: Locale } => { return { locale: baseLocale } });
overwriteGetLocale(() => ssrLocale().locale)

async function getSSRLocale(): Promise<Locale> {
  const cookieStore = await cookies()
  const cookie = cookieStore.get(cookieName)
  if (cookie !== undefined && isLocale(cookie.value)) {
    return cookie.value as Locale
  }
  return baseLocale
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  ssrLocale().locale = await getSSRLocale()

  return (
    <html
      lang={getLocale()}
      className={` h-full antialiased`}
    // ${geistSans.variable} ${geistMono.variable}
    >
      <body className="min-h-dvh flex flex-col">
        <div
          className="fixed inset-0 -z-1 opacity-40
          bg-[linear-gradient(to_right,#e7e5e4_1px,transparent_1px),linear-gradient(to_bottom,#e7e5e4_1px,transparent_1px)]
               bg-size-[40px_40px]
               mask-[radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)]
               [-webkit-mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)]
               print:hidden"
        ></div>

        <LangSelector></LangSelector>

        <Navbar></Navbar>

        {children}

      </body>
    </html>
  );
}
