services:
  cms:
    build:
      dockerfile: ./Dockerfile.cms
    ports:
      - "3001:3000"
    environment:
      - WEBSITE_SECRET=${WEBSITE_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
        - mongodb
  website:
    build: 
      dockerfile: ./Dockerfile.website
    ports:
      - "3000:3000"
    environment:
      - WEBSITE_SECRET=${WEBSITE_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
        - mongodb
  mongodb:
    ports:
      - "27017:27017"
    image: mongo:8.0.4