services:
  cms:
    container_name: cms
    volumes:
      - medias:/app/cms/media
    build:
      dockerfile: ./Dockerfile
      target: cms
    environment:
      - HOSTNAME=0.0.0.0
      - WEBSITE_SECRET=${WEBSITE_SECRET}
      - DATABASE_URL=mongodb://database/website
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - database
    networks:
      - default
      - aquabx-network

  website:
    container_name: website
    build:
      dockerfile: ./Dockerfile
      target: website
    environment:
      - WEBSITE_SECRET=${WEBSITE_SECRET}
      - DATABASE_URL=mongodb://database/website
      - PUBLIC_CMS_URL=https://cms.${DOMAIN_NAME}
      - PUBLIC_DOMAIN_NAME=https://${DOMAIN_NAME}
    depends_on:
      - database
    networks:
      - default
      - aquabx-network

  database:
    image: mongo:latest
    volumes:
      - database:/data/db
    networks:
      - default

volumes:
  database:
  medias:


networks:
  aquabx-network:
    external: true