FROM oven/bun:alpine AS build

WORKDIR /build

COPY . .

WORKDIR /build/website
RUN bun install --frozen-lockfile
RUN bun run build

FROM oven/bun:alpine AS website

WORKDIR /app

COPY ./website/package.json .
COPY --from=build /build/website/build ./dist

RUN bun i -p

CMD ["bun","dist/index.js"]