FROM oven/bun:alpine AS build

WORKDIR /build

COPY . .

WORKDIR /build/cms
RUN bun install --frozen-lockfile

WORKDIR /build/cms/node_modules/adapter-bun
RUN bun install
RUN bun run build

WORKDIR /build/cms
RUN bun run build

FROM oven/bun:alpine AS cms

WORKDIR /app

COPY ./cms/package.json .
COPY --from=build /build/cms/bun-dist ./dist
COPY --from=build /build/cms/.next ./.next

RUN bun i -p

CMD ["bun","dist/server.js"]