// This file is generated by vinext. Do not edit.
import type * as React from "react";

declare global {
  type PageProps<Route extends VinextRouteTypes.PageRoute = VinextRouteTypes.PageRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
    searchParams: Promise<Record<string, string | string[] | undefined>>;
  };

  type LayoutProps<Route extends VinextRouteTypes.LayoutRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
    children: React.ReactNode;
  } & {
    [K in VinextRouteTypes.LayoutSlotMap[Route]]: React.ReactNode;
  };

  type RouteContext<Route extends VinextRouteTypes.RouteHandlerRoute = VinextRouteTypes.RouteHandlerRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
  };
}

declare namespace VinextRouteTypes {
  type PageRoute = "/" | "/admin/[[...segments]]" | "/blog" | "/projects";
  type LayoutRoute = "/(frontend)" | "/(payload)";
  type RouteHandlerRoute = "/api/[...slug]" | "/api/graphql" | "/api/graphql-playground";
  type AppRoute = "/" | "/(frontend)" | "/(payload)" | "/admin/[[...segments]]" | "/api/[...slug]" | "/api/graphql" | "/api/graphql-playground" | "/blog" | "/projects";

  interface ParamMap {
    "/": {};
    "/(frontend)": {};
    "/(payload)": {};
    "/admin/[[...segments]]": { segments?: string[]; };
    "/api/[...slug]": { slug: string[]; };
    "/api/graphql": {};
    "/api/graphql-playground": {};
    "/blog": {};
    "/projects": {};
  }

  interface LayoutSlotMap {
    "/(frontend)": never;
    "/(payload)": never;
  }
}



export {};
